version: "3"
services:
  postgres:
    image: postgres:9.6.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payments
  payments:
    image: bozen/payments
    ports:
      - 8090:8090
    environment:
      KUMULUZEE_DATASOURCES0_CONNECTIONURL: jdbc:postgresql://postgres:5432/payment
    depends_on:
      - postgres