kumuluzee:
  name: payments
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8084
    http:
      port: 8084
  datasources:
    - jndi-name: jdbc/PaymentsDS
      connection-url: jdbc:postgresql://192.168.99.100:5432/payment
      username: dbuser
      password: postgres
      max-pool-size: 20
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
  cors-filter:
    servlet:
      allow-origin: "*"
  metrics:
      web-instrumentation:
        - name: payments-endpoint
          url-pattern: /v1/payments/*
rest-properties:
  external-services:
    order-service:
      enabled: true
